networks:
  shared:

services:
  db_postgresql:
    image: ankane/pgvector:latest     # <-- ESSA É A MÁGICA
    container_name: pgvector
    networks:
      - shared
    environment:
      DB_HOST: db_postgresql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  admin:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - shared
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - db_postgresql

volumes:
  postgres_data:
